// the main layout file for the whole application can chnage the font etc for the whole application here 
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/providers/theme-provider'
const inter = Inter({ subsets: ['latin'] })
import { cn } from '@/lib/utils'
import { ModalProvider } from '@/components/providers/modal-provider'
import { SocketProvider } from '@/components/providers/socket-provider'
import { QueryProvider } from '@/components/providers/query-provider'
export const metadata: Metadata = {
  title: 'Discord clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // 3.1 authenticate :  wrap up the whole application with clerk provider  in the root layout 
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      {/*4.5 we are adding the cn class here to make the app color greyish instead of black */}
      <body className={cn(inter.className,
      "bg-white dark:bg-[#313338]")}>
         {/* 4.2 dark and light mode : theme provider  */}
          {/* enabling hte system true we get the third opetion in the mode toggle for chnaing the theme of the whole appplication  */}
      <ThemeProvider
       attribute='class'
      defaultTheme='dark'
      enableSystem={false}
      storageKey='discord-theme'>
       {/** 24.2importing the socket provider here  */}
       <SocketProvider>
       {/**importing the modl here  */} 
       <ModalProvider />
       {/* 27.5 wrapping the children inside of the query prcd.  */}
     <QueryProvider>
     {children}
     </QueryProvider>
        </SocketProvider>
        </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  )
}
